alias: Create csv file for Grafana dashboard use pyscript
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.face_detected_occurrence
conditions: []
actions:
  - variables:
      target_dir: "{{trigger.to_state.attributes.path}}"
      csv_out_file: /config/www/grafana/{{trigger.to_state.state|lower}}.csv
  - action: pyscript.list_directory
    data:
      directory: "{{target_dir}}"
      output_file: "{{csv_out_file}}"
    continue_on_error: true
mode: single
